apiVersion: v1
kind: Service
metadata:
  name: cricketerinfo-service
spec:
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: NodePort
  selector:
    app: cricketerinfo


